"""Playback of generated speech functions."""
import tempfile
import logging
from subprocess import call

from playsound import playsound


_LOGGER = logging.getLogger(__name__)


def google(config, speech):
    """Play speech generated by google."""
    with tempfile.NamedTemporaryFile() as temp:
        try:
            speech.write_to_fp(temp)
            playsound(temp.name)
        except AttributeError:
            _LOGGER.error("No sound to play")

def apple_say(config, speech):
    """Play speech with the `say` command on MacOS."""
    try:
        call(["say", "-v", config["voice"], speech])
    except KeyError:
        call(["say", speech])
